function initMixins() {

	chance.mixin({
		'companyName': function() {
			return chance.last() + " " + chance.pick(['SP','GP','LP','Corporation','Joint Venture','Limited','Incorporated','Ltd.','Corp.','Inc.','Company.']);
		},
		'companyIndustry': function() {
			return chance.pick(["Accident & Health Insurance","Advertising Agencies","Aerospace/Defense Products & Services","Agricultural Chemicals","Air Delivery & Freight Services","Apparel Stores","Appliances","Application Software","Asset Management","Auto Dealerships","Auto Manufacturers","Auto Parts","Brewers","Soft Drinks","Biotechnology","Radio Broadcasting","Television Broadcasting","Business Equipment","Business Services","Business Software & Services","CATV Systems","Cement","Chemicals","Cigarettes","Communication Equipment","Computer Based Systems","Confectioners","Consumer Services","Dairy Products","Data Storage Devices","Department Stores","Drug Manufacturers","Drug Stores","Education & Training Services","Electric Utilities","Electronic Equipment","Electronics Stores","Entertainment","Farm & Construction Machinery","Farm Products","Food","Food Wholesale","Foreign Money Center Banks","Foreign Regional Banks","Gaming Activities","Gas Utilities","General Building Materials","General Contractors","General Entertainment","Grocery Stores","Healthcare Information Services","Heavy Construction","Home Furnishing Stores","Home Improvement Stores","Hospitals","Housewares & Accessories","Independent Oil & Gas","Industrial Electrical Equipment","Industrial Metals & Minerals","Information Technology Services","Insurance Brokers","Internet Service Providers","Internet Software & Services","Investment Brokerage","Life Insurance","Lodging","Lumber, Wood Production","Machine Tools & Accessories","Major Airlines","Major Integrated Oil & Gas","Management Services","Marketing Services","Meat Products","Medical Appliances & Equipment","Medical Instruments & Supplies","Medical Laboratories & Research","Metal Fabrication","Mortgage Investment","Multimedia & Graphics Software","Music & Video Stores","Networking & Communication Devices","Office Supplies","Oil & Gas","Paper & Paper Products","Pharmaceuticals","Property","Property Management","Publishing","Railroads","Real Estate Development","Recreational Vehicles","Rental & Leasing Services","Research Services","Residential Construction","Resorts & Casinos","Restaurants","Rubber & Plastics","Savings & Loans","Scientific & Technical Instruments","Security & Protection Services","Security Software & Services","Semiconductor","Shipping","Silver","Small Tools & Accessories","Sporting Activities","Sporting Goods","Staffing & Outsourcing Services","Steel & Iron","Synthetics","Technical & System Software","Technical Services","Telecom Services","Textile","Toy & Hobby Stores","Toys & Games","Trucking","Waste Management","Water Utilities","Wireless Communications"])
		}
	});

}
		
